### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by NandhiniAnne** [INFO523-S24/project-01-Algo-Aces#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Nandhini Anne - @NandhiniAnne
- Sunday Usman - @sundayusman
- H M Abdul Fattah - @hmfattah
- Shreemithra Naveen - @shreemithran
- Srinivasan Poonkundran - @kANNISTER

- Describe the goal of the project.

The goal of the project is to understand the nutritional pattern and trends of different individuals. Furthermore, results gotten from the analysis will be used to make more informed decision about dietary choices as well as help to promote health awareness.

- Describe the data used or collected.

The dataset used contains many columns with various variables of fast food items, such as restaurant, category, calorie count, fat content, protein content, carbohydrate content, and so on. The number of rows represents the number of individual fast food items for each restaurant in the dataset.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

Question 1 can be answered by filtering the dataset for each restaurant, then aggregating calorie information, and then computing the average number of calories per item and comparing it to other restaurants.

Question 2 can be answered by categorizing food items, then aggregating nutritional information, and then presenting the data with plots, charts, or graphs.

- Is there anything that is unclear from the proposal?

We couldn't clearly figure out which variables were categorical and which were numerical. 

- Provide constructive feedback on how the team might be able to improve their project.

Based on the proposal, the team appears to be working on something really interesting. This study could assist promote healthy eating habits among people of various socioeconomic backgrounds. However, we were curious as to why the variable "calories" in the dataset is not included and is also utilized to answer the question 1. What is the purpose of the calories variable?

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

It would be interesting to see the various calories contained in the foods we consume on a regular basis, as well as compare those numbers to those published on them by various fast food companies.

- Provide constructive feedback on any issues with file and/or code organization.

Nice work, all the csv files are included in the data folder accordingly.

- (Optional) Any further comments or feedback?

**Comment by navyaa-reddy** [comment]
Thank you for the feedback. 
1."We couldn't clearly figure out which variables were categorical and which were numerical"  We have added whether the variables are categorical or numerical. 
2."we were curious as to why the variable "calories" in the dataset is not included and is also utilized to answer the question 1" 
The 'calories' variable is necessary for answering Question 1 because it's essential for comparing the average number of calories per item across different restaurants.
