### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by tezz-us** [INFO523-S24/project-01-Algo-Aces#2]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

-  Ayesha Khatun - @ayeshakhatunsujana
-  Alyssa Nether - @rlyalyther
-  Akash Srinivasan - @AkashSrinivasan12
-  Tejas Bhawari -  @tezz-us
-  Gabriel Geffen - @gabegef

- Describe the goal of the project.
Algo Aces examines a "Fast Food Calories" dataset that provides ample information discussing the nutritional information associated with various fast food chains and the food that is offered. The objectives of this group are to examine nutritional information of various fast food items in comparison to various national standards or across other companies. To further explain, they will first compare average calories to examine overall health among different chains. Following this, they will examine the protein to fat ratio of unmentioned food items in comparison to some external health metric.Utilizing the groupby.describe() function, they will create a summary statistics table for each restaurant item's calorie count. They will then calculate the average calories per item per each restaurant. They then plan to use a half violin plot to showcase the distribution results of the average calories.

- Describe the data used or collected.
The "Fast Food Calories" dataset includes nutritional information for menu items from eight fast-food outlets, covering burgers, fries, beverages, and salads. It provides key metrics like calories, fat, protein, and carbohydrates, enabling quick and comprehensive analysis for research, health guidance, and informed consumer choices.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
they will be doing 5 different comparisons between earnings and the rest of the variables (time, genre, duration, title length, rating and release year). all comparisons will be seeing if changing variables will lead to higher earnings.

- Is there anything that is unclear from the proposal?
The project could include an external data file consisting research institutions or open data repositories. The variables provided have unclear description and also it would be useful to include a section on how the results of the analysis will be interpreted and what insights can be derived from them.

- Provide constructive feedback on how the team might be able to improve their project.
If ensured transparency by clearly specifying the dataset's origin and providing a link for reproducibility, detailing specific steps for data cleaning and validation to ensure accuracy, explaining the rationale behind variable selection and defining them clearly, providing information on statistical methods used and any underlying assumptions, including a section on interpreting results to discuss implications and practical relevance, exploring a variety of visualization techniques beyond half violin plots for deeper insights.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
Highlighting the health implications of fast food consumption based on the nutritional analysis of popular fast food items. trends observed in the fast food industry based on the analysis of the dataset. Also showcasing how different fast food outlets compare in terms of aaverage per visit to each restaurant or outlet and different food item categories which vary in protien-fat ratio and if they meet up to the standards of the health metric.

- Provide constructive feedback on any issues with file and/or code organization.
In README.md file you have to upload the description of the dataset's variables, In the project instruction website, professor mentioned it to do this. If the data cleansing portion's code is published on github, they can add it. They attempted to utilise a bullet to respond to the question "Why this dataset?" Sadly, it did not function correctly in the rendered file.
Some spaces are missing, please correct it, for example "Q1) How many calories areconsumed on average per visit to each restaurant or outlet?" there will be a space after are.

**Comment by navyaa-reddy** [comment]
Thank you for your feedback.
1."The variables provided have unclear description and also it would be useful to include a section on how the results of the analysis will be interpreted and what insights can be derived from them". We have included the description of the datasets variables.
2."They attempted to utilize a bullet to respond to the question "Why this dataset?" Sadly, it did not function correctly in the rendered file." Addressed the issue.
3."they will be doing 5 different comparisons between earnings and the rest of the variables (time, genre, duration, title length, rating and release year). all comparisons will be seeing if changing variables will lead to higher earnings." Not related to our project proposal.
4."If ensured transparency by clearly specifying the dataset's origin and providing a link for reproducibility, detailing specific steps for data cleaning and validation to ensure accuracy, explaining the rationale behind variable selection and defining them clearly, providing information on statistical methods used and any underlying assumptions, including a section on interpreting results to discuss implications and practical relevance, exploring a variety of visualization techniques beyond half violin plots for deeper insights."  We have mentioned the origin of the dataset. Regarding the data cleaning, validation steps we can't give you the specific details at this point of time cause the data is yet to be analyzed. We have also updated the variable description clearly. Regarding the selection of half-violin plot, we feel it's the best to visualize our question. But if need be we will look into using other plots for this analysis.
