### ISSUE TITLE
Proposal resubmission for a Regrade

### ISSUE THREAD

**Issue by tanyageorge** [INFO523-S24/project-01-Algo-Aces#4]
We worked on the things pointed out and added them as best as we could.  The additions were explained in relations to the respective questions. A left join for question 2 was added as instructed  as well as a timeline for the project. We will try to work better and with more detail for the project and presentation. Thank you for your feedback

**Comment by Gchism94** [comment]
I checked your proposal again. Your second score is **10/10**, so the final score is **9.25/10**
